// <auto-generated />
using System;
using Anna_E_Seo_301098222.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anna_E_Seo_301098222.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200325062915_PlayerMigrations")]
    partial class PlayerMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anna_E_Seo_301098222.Models.Club", b =>
                {
                    b.Property<string>("clubName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<int?>("nDraws");

                    b.Property<int?>("nWins");

                    b.Property<string>("nation");

                    b.Property<string>("sponsor");

                    b.Property<int?>("totalPoints");

                    b.HasKey("clubName");

                    b.ToTable("clubitems");
                });

            modelBuilder.Entity("Anna_E_Seo_301098222.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Club");

                    b.Property<int>("JersyNumber");

                    b.Property<int>("Rank");

                    b.Property<int>("totalGoals");

                    b.HasKey("Name");

                    b.ToTable("playeritems");
                });
#pragma warning restore 612, 618
        }
    }
}
